name: Slither

on: [push, pull_request]

jobs:
  analyze:
    name: Slither
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Slither
      uses: crytic/slither-action@fix-nvm-install
      with:
        node-version: 12
